export const layout = {
  abs: {
    position: 'absolute' as const,
  },
  alignCtr: {
    alignItems: 'center' as const,
  },
  alignEnd: {
    alignItems: 'flex-end' as const,
  },
  alignStart: {
    alignItems: 'flex-start' as const,
  },
  alignStretch: {
    alignItems: 'stretch' as const,
  },
  flex: {
    flex: 1,
  },
  flexRow: {
    flexDirection: 'row' as const,
  },
  flexCol: {
    flexDirection: 'column' as const,
  },
  flexCenter: {
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  fullSize: {
    height: '100%' as const,
    width: '100%' as const,
  },
  fullWidth: {
    width: '100%' as const,
  },
  fullHeight: {
    height: '100%' as const,
  },
  justifyArnd: {
    justifyContent: 'space-around' as const,
  },
  justifyBtw: {
    justifyContent: 'space-between' as const,
  },
  justifyCtr: {
    justifyContent: 'center' as const,
  },
  justifyEnd: {
    justifyContent: 'flex-end' as const,
  },
  justifyStrt: {
    justifyContent: 'flex-start' as const,
  },
  wrap: {
    flexWrap: 'wrap' as const,
  },
  defaultBorderRadius: {
    borderRadius: 5,
  },
  absoluteFill: {
    position: 'absolute' as const,
    bottom: 0,
    top: 0,
    right: 0,
    left: 0,
  },

  m5: {margin: 5},
  ml5: {marginLeft: 5},
  mr5: {marginRight: 5},
  mt5: {marginTop: 5},
  mb5: {marginBottom: 5},
  mx5: {marginHorizontal: 5},
  my5: {marginVertical: 5},
  p5: {padding: 5},
  pl5: {paddingLeft: 5},
  pr5: {paddingRight: 5},
  pt5: {paddingTop: 5},
  pb5: {paddingBottom: 5},
  px5: {paddingHorizontal: 5},
  py5: {paddingVertical: 5},

  m10: {margin: 10},
  ml10: {marginLeft: 10},
  mr10: {marginRight: 10},
  mt10: {marginTop: 10},
  mb10: {marginBottom: 10},
  mx10: {marginHorizontal: 10},
  my10: {marginVertical: 10},
  p10: {padding: 10},
  pl10: {paddingLeft: 10},
  pr10: {paddingRight: 10},
  pt10: {paddingTop: 10},
  pb10: {paddingBottom: 10},
  px10: {paddingHorizontal: 10},
  py10: {paddingVertical: 10},

  m15: {margin: 15},
  ml15: {marginLeft: 15},
  mr15: {marginRight: 15},
  mt15: {marginTop: 15},
  mb15: {marginBottom: 15},
  mx15: {marginHorizontal: 15},
  my15: {marginVertical: 15},
  p15: {padding: 15},
  pl15: {paddingLeft: 15},
  pr15: {paddingRight: 15},
  pt15: {paddingTop: 15},
  pb15: {paddingBottom: 15},
  px15: {paddingHorizontal: 15},
  py15: {paddingVertical: 15},

  m20: {margin: 20},
  ml20: {marginLeft: 20},
  mr20: {marginRight: 20},
  mt20: {marginTop: 20},
  mb20: {marginBottom: 20},
  mb25: {marginBottom: 25},
  mx20: {marginHorizontal: 20},
  my20: {marginVertical: 20},
  p20: {padding: 20},
  pl20: {paddingLeft: 20},
  pr20: {paddingRight: 20},
  pt20: {paddingTop: 20},
  pb20: {paddingBottom: 20},
  px20: {paddingHorizontal: 20},
  py20: {paddingVertical: 20},

  m30: {margin: 30},
  ml30: {marginLeft: 30},
  mr30: {marginRight: 30},
  mt30: {marginTop: 30},
  mb30: {marginBottom: 30},
  mx30: {marginHorizontal: 30},
  my30: {marginVertical: 30},
  p30: {padding: 30},
  pl30: {paddingLeft: 30},
  pr30: {paddingRight: 30},
  pt30: {paddingTop: 30},
  pb30: {paddingBottom: 30},
  px30: {paddingHorizontal: 30},
  py30: {paddingVertical: 30},

  m40: {margin: 40},
  ml40: {marginLeft: 40},
  mr40: {marginRight: 40},
  mt40: {marginTop: 40},
  mb40: {marginBottom: 40},
  mx40: {marginHorizontal: 40},
  my40: {marginVertical: 40},
  p40: {padding: 40},
  pl40: {paddingLeft: 40},
  pr40: {paddingRight: 40},
  pt40: {paddingTop: 40},
  pb40: {paddingBottom: 40},
  px40: {paddingHorizontal: 40},
  py40: {paddingVertical: 40},

  m50: {margin: 50},
  ml50: {marginLeft: 50},
  mr50: {marginRight: 50},
  mt50: {marginTop: 50},
  mb50: {marginBottom: 50},
  mx50: {marginHorizontal: 50},
  my50: {marginVertical: 50},
  p50: {padding: 50},
  pl50: {paddingLeft: 50},
  pr50: {paddingRight: 50},
  pt50: {paddingTop: 50},
  pb50: {paddingBottom: 50},
  px50: {paddingHorizontal: 50},
  py50: {paddingVertical: 50},
};
